on:
  schedule:
  # should run at midnight 1st day of each month
    - cron:  '0 0 1 * *'
  push:
    branches:
      - master
      
name: check-for-bioc-updates

jobs:
  check-for-bioc-updates:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set package name as environment variable
      run: |
        echo "PACKAGE_NAME=`basename ${GITHUB_REPOSITORY}`" >> $GITHUB_ENV
    
    - name: Get any missing commits from Bioconductor
      run: |
        git config pull.rebase false
        git --no-pager log -n 4
        git remote add bioc "https://git.bioconductor.org/packages/${PACKAGE_NAME}"
        git fetch --all
        git --no-pager log bioc/master -n 4
        git pull bioc master
        

