on:
  schedule:
  # should run at midnight 1st day of each month
    - cron:  '0 0 1 * *'
  push:
    branches:
      - master
      
name: check-for-bioc-updates

jobs:
  check-for-bioc-updates:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Get any missing commits from Bioconductor
      run: |
        git remote add bioc https://git.bioconductor.org/packages/
        git fetch --all
        git pull bioc master
        git push origin master || echo "No changes to commit"
        

